name: todo_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  build_runner: ^2.4.14
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
